import { Question } from '@/types';

export const biologyQuestions: Question[] = [
  {
    id: 'bio-cell-1',
    subject: 'biology',
    chapter: 'cell-division',
    topic: 'Mitosis',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'State two differences between mitosis and meiosis.',
    correctAnswer: '1. Mitosis produces 2 identical daughter cells; meiosis produces 4 genetically different daughter cells. 2. Mitosis maintains chromosome number (diploid); meiosis halves it (haploid).',
    explanation: 'Mitosis is for growth and repair. Meiosis is for gamete formation.',
    commonErrors: ['Saying meiosis produces 2 cells', 'Not specifying diploid vs haploid'],
  },
  {
    id: 'bio-cell-2',
    subject: 'biology',
    chapter: 'cell-division',
    topic: 'Cell Cycle',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'DNA replication occurs during which phase of the cell cycle?',
    options: ['S phase (Synthesis)', 'G1 phase', 'M phase', 'G2 phase'],
    correctAnswer: 'S phase (Synthesis)',
    explanation: 'The S (Synthesis) phase is when DNA replication occurs, doubling the genetic material before cell division.',
  },
  {
    id: 'bio-cell-3',
    subject: 'biology',
    chapter: 'cell-division',
    topic: 'Mitosis',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Describe the events that occur during the metaphase of mitosis.',
    correctAnswer: 'During metaphase: (1) Chromosomes align at the equatorial plate/metaphase plate of the cell. (2) Spindle fibres attach to the centromere of each chromosome. (3) Each chromosome consists of two sister chromatids joined at the centromere.',
    explanation: 'Metaphase is when chromosomes are most visible and condensed, making it ideal for karyotyping.',
  },
  {
    id: 'bio-gen-1',
    subject: 'biology',
    chapter: 'genetics',
    topic: "Mendel's Laws",
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: "State Mendel's Law of Segregation and give an example.",
    correctAnswer: "Mendel's Law of Segregation states that during gamete formation, the two alleles of a gene separate (segregate) from each other so that each gamete receives only one allele. Example: In a Tt (tall) plant, gametes will be either T or t, not Tt.",
    explanation: 'This is also known as the Law of Purity of Gametes.',
    commonErrors: ['Confusing with Law of Independent Assortment', 'Not providing a clear example'],
  },
  {
    id: 'bio-gen-2',
    subject: 'biology',
    chapter: 'genetics',
    topic: 'Monohybrid Cross',
    type: 'numerical',
    difficulty: 'medium',
    marks: 4,
    question: 'In pea plants, tall (T) is dominant over dwarf (t). Cross a heterozygous tall plant with a dwarf plant. Give the phenotypic and genotypic ratios of the offspring.',
    correctAnswer: 'Genotypic ratio: 1 Tt : 1 tt. Phenotypic ratio: 1 Tall : 1 Dwarf (1:1).',
    explanation: 'Tt × tt cross: Gametes of Tt are T and t. Gametes of tt are t and t. Offspring: Tt (tall), Tt (tall... no). Let me redo: Tt × tt → Tt, Tt, tt, tt. No: Tt × tt → T×t=Tt, T×t=Tt, t×t=tt, t×t=tt. Wait, gametes from Tt: T, t. Gametes from tt: t, t. So offspring: Tt, tt, Tt, tt → 2Tt : 2tt = 1:1.',
    markScheme: '1 mark for correct gametes, 1 mark for Punnett square, 1 mark for genotypic ratio, 1 mark for phenotypic ratio',
  },
  {
    id: 'bio-gen-3',
    subject: 'biology',
    chapter: 'genetics',
    topic: 'Sex Determination',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'In humans, sex is determined by:',
    options: ['Sex chromosomes from the father', 'Sex chromosomes from the mother', 'Autosomes', 'Mitochondrial DNA'],
    correctAnswer: 'Sex chromosomes from the father',
    explanation: 'The father can contribute either X or Y chromosome. Mother always contributes X. If sperm carries X → XX (girl). If sperm carries Y → XY (boy).',
  },
  {
    id: 'bio-plant-1',
    subject: 'biology',
    chapter: 'plant-physiology',
    topic: 'Photosynthesis',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Write the balanced chemical equation for photosynthesis. Name the two stages and where each occurs.',
    correctAnswer: '6CO₂ + 6H₂O → (light energy, chlorophyll) → C₆H₁₂O₆ + 6O₂. Light reaction occurs in the grana (thylakoids) of chloroplast. Dark reaction (Calvin cycle) occurs in the stroma of chloroplast.',
    explanation: 'Photosynthesis has two stages: light-dependent reactions (need light) and light-independent reactions (Calvin cycle).',
    commonErrors: ['Writing unbalanced equation', 'Saying dark reaction needs darkness (it just doesn\'t need light directly)'],
  },
  {
    id: 'bio-plant-2',
    subject: 'biology',
    chapter: 'plant-physiology',
    topic: 'Transpiration',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Most transpiration in plants occurs through:',
    options: ['Stomata', 'Cuticle', 'Lenticels', 'Root hairs'],
    correctAnswer: 'Stomata',
    explanation: 'About 90% of transpiration occurs through stomata on the leaf surface. Cuticular transpiration accounts for a small percentage.',
  },
  {
    id: 'bio-plant-3',
    subject: 'biology',
    chapter: 'plant-physiology',
    topic: 'Absorption by Roots',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'Define osmosis. Why is it important for root hair cells?',
    correctAnswer: 'Osmosis is the movement of water molecules from a region of higher water concentration to a region of lower water concentration through a semi-permeable membrane. Root hair cells absorb water from the soil by osmosis because the cell sap has a lower water concentration than the soil solution.',
    explanation: 'The cell sap in root hair cells is more concentrated than soil water, creating an osmotic gradient.',
  },
  {
    id: 'bio-anat-1',
    subject: 'biology',
    chapter: 'human-anatomy',
    topic: 'Circulatory System',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'State three differences between arteries and veins.',
    correctAnswer: '1. Arteries carry oxygenated blood (except pulmonary artery); veins carry deoxygenated blood (except pulmonary vein). 2. Arteries have thick, muscular walls; veins have thin walls. 3. Arteries have no valves; veins have valves to prevent backflow.',
    explanation: 'Arteries carry blood away from the heart; veins carry blood towards the heart.',
    commonErrors: ['Saying all arteries carry oxygenated blood (pulmonary artery is an exception)', 'Forgetting to mention valves'],
  },
  {
    id: 'bio-anat-2',
    subject: 'biology',
    chapter: 'human-anatomy',
    topic: 'Nervous System',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which part of the brain controls balance and coordination?',
    options: ['Cerebellum', 'Cerebrum', 'Medulla oblongata', 'Hypothalamus'],
    correctAnswer: 'Cerebellum',
    explanation: 'The cerebellum is responsible for balance, posture, and coordination of voluntary movements.',
  },
  {
    id: 'bio-anat-3',
    subject: 'biology',
    chapter: 'human-anatomy',
    topic: 'Excretory System',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Describe the three main steps in urine formation in the nephron.',
    correctAnswer: '1. Ultrafiltration: Blood is filtered in the glomerulus; glucose, amino acids, salts, water, and urea pass into Bowman\'s capsule. 2. Selective reabsorption: Useful substances (glucose, amino acids, some water and salts) are reabsorbed in the proximal tubule. 3. Tubular secretion: Additional waste substances are secreted into the tubule from blood capillaries.',
    explanation: 'The nephron is the functional unit of the kidney.',
  },
  {
    id: 'bio-eco-1',
    subject: 'biology',
    chapter: 'ecology',
    topic: 'Food Chain',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'In a food chain, the 10% law states that:',
    options: [
      'Only 10% of energy is transferred to the next trophic level',
      '10% of organisms survive at each level',
      '10% of food is wasted',
      'Only 10% of species are producers',
    ],
    correctAnswer: 'Only 10% of energy is transferred to the next trophic level',
    explanation: 'The 10% law (Lindeman\'s law) states that only about 10% of energy is transferred from one trophic level to the next. The rest is lost as heat through respiration.',
  },
  {
    id: 'bio-eco-2',
    subject: 'biology',
    chapter: 'ecology',
    topic: 'Pollution',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'What is the greenhouse effect? Name two greenhouse gases.',
    correctAnswer: 'The greenhouse effect is the trapping of heat by certain gases in the atmosphere, which warm the Earth\'s surface. Two greenhouse gases: Carbon dioxide (CO₂) and Methane (CH₄).',
    explanation: 'While the greenhouse effect is natural and necessary, enhanced greenhouse effect due to human activities leads to global warming.',
  },
  {
    id: 'bio-cell-4',
    subject: 'biology',
    chapter: 'cell-division',
    topic: 'Meiosis',
    type: 'mcq',
    difficulty: 'medium',
    marks: 1,
    question: 'Crossing over occurs during which stage of meiosis?',
    options: ['Pachytene of Prophase I', 'Metaphase I', 'Anaphase II', 'Telophase I'],
    correctAnswer: 'Pachytene of Prophase I',
    explanation: 'Crossing over (exchange of genetic material between homologous chromosomes) occurs during the pachytene stage of Prophase I in meiosis.',
  },
  {
    id: 'bio-gen-4',
    subject: 'biology',
    chapter: 'genetics',
    topic: 'Dihybrid Cross',
    type: 'mcq',
    difficulty: 'medium',
    marks: 1,
    question: 'The phenotypic ratio of a dihybrid cross (F₂ generation) is:',
    options: ['9:3:3:1', '3:1', '1:2:1', '1:1:1:1'],
    correctAnswer: '9:3:3:1',
    explanation: 'In a dihybrid cross between two heterozygous parents (AaBb × AaBb), the F₂ generation shows a 9:3:3:1 phenotypic ratio.',
  },
  {
    id: 'bio-gen-5',
    subject: 'biology',
    chapter: 'genetics',
    topic: 'Inherited Traits',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'What is the difference between homozygous and heterozygous conditions? Give examples.',
    correctAnswer: 'Homozygous: Both alleles for a gene are the same (e.g., TT for tall or tt for dwarf). Heterozygous: The two alleles for a gene are different (e.g., Tt for tall).',
    explanation: 'Homozygous organisms are pure-breeding; heterozygous organisms are hybrids.',
  },
  {
    id: 'bio-plant-4',
    subject: 'biology',
    chapter: 'plant-physiology',
    topic: 'Photosynthesis',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which pigment is primarily responsible for absorbing light during photosynthesis?',
    options: ['Chlorophyll', 'Xanthophyll', 'Carotenoid', 'Anthocyanin'],
    correctAnswer: 'Chlorophyll',
    explanation: 'Chlorophyll (mainly chlorophyll-a) is the primary photosynthetic pigment. It absorbs red and blue light and reflects green light.',
  },
  {
    id: 'bio-plant-5',
    subject: 'biology',
    chapter: 'plant-physiology',
    topic: 'Transpiration',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'List three factors that affect the rate of transpiration.',
    correctAnswer: '1. Temperature: Higher temperature increases transpiration rate. 2. Humidity: Lower humidity increases transpiration rate. 3. Wind speed: Higher wind speed increases transpiration rate by removing water vapour from around the leaf.',
    explanation: 'Other factors include light intensity (stomata open in light) and soil water availability.',
    commonErrors: ['Not explaining how each factor affects the rate', 'Confusing humidity effect (lower humidity = more transpiration)'],
  },
  {
    id: 'bio-anat-4',
    subject: 'biology',
    chapter: 'human-anatomy',
    topic: 'Eye',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Name the part of the eye that: (a) controls the amount of light entering, (b) focuses light onto the retina, (c) contains photoreceptor cells.',
    correctAnswer: '(a) Iris — it controls the size of the pupil. (b) Lens (crystalline lens) — it changes shape to focus light (accommodation). (c) Retina — it contains rods (dim light) and cones (colour vision).',
    explanation: 'The eye works like a camera: the iris is the aperture, the lens focuses, and the retina is the film/sensor.',
    commonErrors: ['Confusing iris with pupil', 'Saying cornea instead of lens for focusing'],
  },
  {
    id: 'bio-anat-5',
    subject: 'biology',
    chapter: 'human-anatomy',
    topic: 'Endocrine System',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Insulin is secreted by:',
    options: ['Pancreas (Islets of Langerhans)', 'Thyroid gland', 'Adrenal gland', 'Pituitary gland'],
    correctAnswer: 'Pancreas (Islets of Langerhans)',
    explanation: 'Insulin is secreted by the beta cells of the Islets of Langerhans in the pancreas. It lowers blood sugar level.',
  },
  {
    id: 'bio-anat-6',
    subject: 'biology',
    chapter: 'human-anatomy',
    topic: 'Respiratory System',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Explain the mechanism of breathing (inspiration and expiration) in humans.',
    correctAnswer: 'Inspiration: Diaphragm contracts and flattens, external intercostal muscles contract, rib cage moves up and out, thoracic cavity volume increases, pressure decreases, air rushes in. Expiration: Diaphragm relaxes and becomes dome-shaped, internal intercostal muscles contract, rib cage moves down and in, volume decreases, pressure increases, air is pushed out.',
    explanation: 'Breathing is a mechanical process based on pressure differences caused by changes in thoracic cavity volume.',
    commonErrors: ['Not mentioning role of diaphragm', 'Confusing inspiration with expiration mechanisms'],
  },
  {
    id: 'bio-eco-3',
    subject: 'biology',
    chapter: 'ecology',
    topic: 'Ecosystem',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What is a food web? How is it different from a food chain?',
    correctAnswer: 'A food web is a network of interconnected food chains in an ecosystem, showing the complex feeding relationships among organisms. Unlike a food chain (which is a single linear pathway of energy transfer), a food web shows that most organisms feed on more than one type of food and are eaten by more than one predator.',
    explanation: 'Food webs are more realistic representations of energy flow in ecosystems than simple food chains.',
  },
];
