import { Question } from '@/types';

export const chemistryQuestions: Question[] = [
  {
    id: 'chem-pt-1',
    subject: 'chemistry',
    chapter: 'periodic-table',
    topic: 'Periods and Groups',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The element with atomic number 11 belongs to which group and period?',
    options: ['Group 1, Period 3', 'Group 1, Period 2', 'Group 11, Period 1', 'Group 2, Period 3'],
    correctAnswer: 'Group 1, Period 3',
    explanation: 'Atomic number 11 is Sodium (Na). Electronic config: 2,8,1. It has 3 shells (Period 3) and 1 valence electron (Group 1).',
  },
  {
    id: 'chem-pt-2',
    subject: 'chemistry',
    chapter: 'periodic-table',
    topic: 'Trends',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'How does ionisation energy vary (a) across a period, and (b) down a group? Give reasons.',
    correctAnswer: '(a) Increases across a period due to increasing nuclear charge with same number of shells. (b) Decreases down a group due to increasing number of shells and greater shielding effect.',
    explanation: 'Ionisation energy depends on nuclear charge, atomic size, and shielding effect.',
    commonErrors: ['Confusing ionisation energy trend with electronegativity', 'Not mentioning shielding effect for group trend'],
  },
  {
    id: 'chem-bond-1',
    subject: 'chemistry',
    chapter: 'chemical-bonding',
    topic: 'Ionic Bonding',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'What is an ionic bond? Give one example.',
    correctAnswer: 'An ionic bond is formed by the transfer of electrons from a metal to a non-metal atom, resulting in the formation of oppositely charged ions which are held together by electrostatic attraction. Example: NaCl (sodium chloride).',
    explanation: 'In NaCl, Na loses 1 electron to form Na⁺ and Cl gains 1 electron to form Cl⁻.',
  },
  {
    id: 'chem-bond-2',
    subject: 'chemistry',
    chapter: 'chemical-bonding',
    topic: 'Covalent Bonding',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which of the following molecules has a double covalent bond?',
    options: ['O₂', 'H₂', 'Cl₂', 'HCl'],
    correctAnswer: 'O₂',
    explanation: 'Oxygen (O₂) has a double covalent bond (O=O). Each oxygen atom shares 2 electrons to complete its octet.',
  },
  {
    id: 'chem-acid-1',
    subject: 'chemistry',
    chapter: 'acids-bases',
    topic: 'Properties',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which of the following is a strong acid?',
    options: ['HCl', 'CH₃COOH', 'H₂CO₃', 'H₂SO₃'],
    correctAnswer: 'HCl',
    explanation: 'HCl (hydrochloric acid) is a strong acid that completely dissociates in water. CH₃COOH (acetic acid), H₂CO₃ (carbonic acid), and H₂SO₃ (sulphurous acid) are all weak acids.',
  },
  {
    id: 'chem-acid-2',
    subject: 'chemistry',
    chapter: 'acids-bases',
    topic: 'pH Scale',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'What is the pH of a neutral solution? How does pH change when a base is added to water?',
    correctAnswer: 'A neutral solution has pH = 7. When a base is added to water, the pH increases above 7.',
    explanation: 'pH scale ranges from 0-14. pH < 7 is acidic, pH = 7 is neutral, pH > 7 is basic/alkaline.',
  },
  {
    id: 'chem-mole-1',
    subject: 'chemistry',
    chapter: 'mole-concept',
    topic: 'Mole Calculations',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Calculate the number of moles in 44 g of CO₂. (Atomic masses: C = 12, O = 16)',
    correctAnswer: '1 mole',
    explanation: 'Molar mass of CO₂ = 12 + 2(16) = 44 g/mol. Number of moles = mass/molar mass = 44/44 = 1 mole.',
    commonErrors: ['Incorrectly calculating molar mass', 'Forgetting to multiply atomic mass of O by 2'],
  },
  {
    id: 'chem-mole-2',
    subject: 'chemistry',
    chapter: 'mole-concept',
    topic: 'Stoichiometry',
    type: 'numerical',
    difficulty: 'hard',
    marks: 4,
    question: 'How many grams of hydrogen are produced when 46 g of sodium reacts with water?\n2Na + 2H₂O → 2NaOH + H₂\n(Atomic masses: Na = 23, H = 1)',
    correctAnswer: '2 g',
    explanation: '46 g Na = 46/23 = 2 moles Na. From the equation, 2 moles Na produce 1 mole H₂. 1 mole H₂ = 2 g.',
    commonErrors: ['Not balancing the equation first', 'Incorrect mole ratio from equation'],
    markScheme: '1 mark for moles of Na, 1 mark for mole ratio, 1 mark for mass of H₂, 1 mark for units',
  },
  {
    id: 'chem-elec-1',
    subject: 'chemistry',
    chapter: 'electrolysis',
    topic: 'Electrolyte Types',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which of the following is a strong electrolyte?',
    options: ['NaCl solution', 'Sugar solution', 'Alcohol', 'Distilled water'],
    correctAnswer: 'NaCl solution',
    explanation: 'NaCl completely dissociates in water to form Na⁺ and Cl⁻ ions, making it a strong electrolyte. Sugar, alcohol, and distilled water do not form ions.',
  },
  {
    id: 'chem-elec-2',
    subject: 'chemistry',
    chapter: 'electrolysis',
    topic: 'Electrode Reactions',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'During electrolysis of acidified water, write the reaction at the (a) cathode, and (b) anode. Which gas is collected at each electrode?',
    correctAnswer: '(a) Cathode: 2H⁺ + 2e⁻ → H₂ (Hydrogen gas collected). (b) Anode: 4OH⁻ → 2H₂O + O₂ + 4e⁻ (Oxygen gas collected).',
    explanation: 'At the cathode (reduction), hydrogen ions gain electrons. At the anode (oxidation), hydroxide ions lose electrons.',
    commonErrors: ['Swapping cathode and anode reactions', 'Forgetting that cathode = reduction, anode = oxidation'],
  },
  {
    id: 'chem-metal-1',
    subject: 'chemistry',
    chapter: 'metallurgy',
    topic: 'Extraction Methods',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Name the process used to extract: (a) Sodium, (b) Iron, (c) Gold. Give reasons for the method chosen.',
    correctAnswer: '(a) Sodium - Electrolytic reduction (very reactive metal). (b) Iron - Reduction with carbon/coke in blast furnace (moderately reactive). (c) Gold - Found in native/free state (least reactive).',
    explanation: 'The method of extraction depends on the reactivity of the metal. More reactive metals need electrolysis, moderately reactive use carbon reduction, least reactive are found free.',
  },
  {
    id: 'chem-org-1',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'Homologous Series',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The general formula of alkenes is:',
    options: ['CₙH₂ₙ', 'CₙH₂ₙ₊₂', 'CₙH₂ₙ₋₂', 'CₙHₙ'],
    correctAnswer: 'CₙH₂ₙ',
    explanation: 'Alkenes have the general formula CₙH₂ₙ. They contain one C=C double bond. Alkanes are CₙH₂ₙ₊₂ and alkynes are CₙH₂ₙ₋₂.',
  },
  {
    id: 'chem-org-2',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'Functional Groups',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Name the functional group and the homologous series for: (a) CH₃OH, (b) CH₃COOH.',
    correctAnswer: '(a) -OH (hydroxyl group), Alcohols. (b) -COOH (carboxyl group), Carboxylic acids.',
    explanation: 'Functional groups determine the chemical properties of organic compounds.',
  },
  {
    id: 'chem-org-3',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'IUPAC Naming',
    type: 'numerical',
    difficulty: 'medium',
    marks: 2,
    question: 'Give the IUPAC name of: CH₃-CH₂-CH₂-OH',
    correctAnswer: 'Propan-1-ol',
    explanation: '3 carbon chain (prop-) with -OH group on carbon 1. IUPAC name: Propan-1-ol.',
    commonErrors: ['Writing 1-propanol instead of propan-1-ol', 'Numbering from wrong end of chain'],
  },
  {
    id: 'chem-pt-3',
    subject: 'chemistry',
    chapter: 'periodic-table',
    topic: 'Element Properties',
    type: 'mcq',
    difficulty: 'medium',
    marks: 1,
    question: 'Which of the following is the most electronegative element?',
    options: ['Fluorine', 'Chlorine', 'Oxygen', 'Nitrogen'],
    correctAnswer: 'Fluorine',
    explanation: 'Fluorine has the highest electronegativity (3.98 on the Pauling scale) of all elements.',
  },
  {
    id: 'chem-bond-3',
    subject: 'chemistry',
    chapter: 'chemical-bonding',
    topic: 'Electrovalency',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Show the formation of MgCl₂ by electron transfer. (Atomic numbers: Mg = 12, Cl = 17)',
    correctAnswer: 'Mg (2,8,2) loses 2 electrons → Mg²⁺ (2,8). Each Cl (2,8,7) gains 1 electron → Cl⁻ (2,8,8). Two Cl⁻ ions combine with one Mg²⁺ to form MgCl₂.',
    explanation: 'Magnesium has electrovalency of +2 (loses 2 electrons). Chlorine has electrovalency of -1 (gains 1 electron). So 1 Mg combines with 2 Cl.',
    markScheme: '1 mark for Mg electron configuration and ion formation, 1 mark for Cl, 1 mark for combining ratio',
  },
  {
    id: 'chem-acid-3',
    subject: 'chemistry',
    chapter: 'acids-bases',
    topic: 'Neutralisation',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Write the balanced equation for the reaction between sodium hydroxide and sulphuric acid. Name the salt formed.',
    correctAnswer: '2NaOH + H₂SO₄ → Na₂SO₄ + 2H₂O. The salt formed is sodium sulphate.',
    explanation: 'This is a neutralisation reaction. NaOH is a base and H₂SO₄ is a dibasic acid, so 2 moles of NaOH react with 1 mole of H₂SO₄.',
    commonErrors: ['Not balancing the equation', 'Writing NaHSO₄ instead of Na₂SO₄ (incomplete neutralisation)'],
  },
  {
    id: 'chem-mole-3',
    subject: 'chemistry',
    chapter: 'mole-concept',
    topic: 'Gas Laws',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Calculate the volume occupied by 11 g of CO₂ at STP. (Molar volume at STP = 22.4 L, C = 12, O = 16)',
    correctAnswer: '5.6 L',
    explanation: 'Molar mass of CO₂ = 44 g/mol. Moles = 11/44 = 0.25 mol. Volume at STP = 0.25 × 22.4 = 5.6 L.',
  },
  {
    id: 'chem-mole-4',
    subject: 'chemistry',
    chapter: 'mole-concept',
    topic: 'Empirical Formula',
    type: 'numerical',
    difficulty: 'hard',
    marks: 4,
    question: 'A compound contains 40% carbon, 6.7% hydrogen, and 53.3% oxygen by mass. Find its empirical formula. (C = 12, H = 1, O = 16)',
    correctAnswer: 'CH₂O',
    explanation: 'C: 40/12 = 3.33. H: 6.7/1 = 6.7. O: 53.3/16 = 3.33. Ratio = 3.33:6.7:3.33 = 1:2:1. Empirical formula = CH₂O.',
    markScheme: '1 mark for mole calculations, 1 mark for ratio, 1 mark for simplification, 1 mark for formula',
  },
  {
    id: 'chem-elec-3',
    subject: 'chemistry',
    chapter: 'electrolysis',
    topic: 'Applications',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'Name two applications of electrolysis.',
    correctAnswer: '1. Electroplating (coating one metal with another, e.g., silver plating). 2. Extraction of metals (e.g., extraction of aluminium from bauxite by electrolysis of alumina).',
    explanation: 'Electrolysis has many industrial applications including electroplating, metal extraction, purification of metals, and electrotyping.',
  },
  {
    id: 'chem-metal-2',
    subject: 'chemistry',
    chapter: 'metallurgy',
    topic: 'Alloys',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Brass is an alloy of:',
    options: ['Copper and Zinc', 'Copper and Tin', 'Iron and Carbon', 'Aluminium and Copper'],
    correctAnswer: 'Copper and Zinc',
    explanation: 'Brass = Cu + Zn. Bronze = Cu + Sn. Steel = Fe + C. Duralumin = Al + Cu + Mg + Mn.',
  },
  {
    id: 'chem-org-4',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'Isomerism',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What are isomers? Draw the structural formulae of two isomers of C₄H₁₀.',
    correctAnswer: 'Isomers are compounds with the same molecular formula but different structural formulae. Isomers of C₄H₁₀: (1) n-butane: CH₃-CH₂-CH₂-CH₃ (straight chain). (2) Isobutane/2-methylpropane: CH₃-CH(CH₃)-CH₃ (branched chain).',
    explanation: 'C₄H₁₀ has two isomers: n-butane (straight chain) and isobutane (branched chain).',
  },
];
