import { Question } from '@/types';

export const chemistryQuestions: Question[] = [
  {
    id: 'chem-pt-1',
    subject: 'chemistry',
    chapter: 'periodic-table',
    topic: 'Periods and Groups',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The element with atomic number 11 belongs to which group and period?',
    options: ['Group 1, Period 3', 'Group 1, Period 2', 'Group 11, Period 1', 'Group 2, Period 3'],
    correctAnswer: 'Group 1, Period 3',
    explanation: 'Atomic number 11 is Sodium (Na). Electronic config: 2,8,1. It has 3 shells (Period 3) and 1 valence electron (Group 1).',
  },
  {
    id: 'chem-pt-2',
    subject: 'chemistry',
    chapter: 'periodic-table',
    topic: 'Trends',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'How does ionisation energy vary (a) across a period, and (b) down a group? Give reasons.',
    correctAnswer: '(a) Increases across a period due to increasing nuclear charge with same number of shells. (b) Decreases down a group due to increasing number of shells and greater shielding effect.',
    explanation: 'Ionisation energy depends on nuclear charge, atomic size, and shielding effect.',
    commonErrors: ['Confusing ionisation energy trend with electronegativity', 'Not mentioning shielding effect for group trend'],
  },
  {
    id: 'chem-bond-1',
    subject: 'chemistry',
    chapter: 'chemical-bonding',
    topic: 'Ionic Bonding',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'What is an ionic bond? Give one example.',
    correctAnswer: 'An ionic bond is formed by the transfer of electrons from a metal to a non-metal atom, resulting in the formation of oppositely charged ions which are held together by electrostatic attraction. Example: NaCl (sodium chloride).',
    explanation: 'In NaCl, Na loses 1 electron to form Na⁺ and Cl gains 1 electron to form Cl⁻.',
  },
  {
    id: 'chem-bond-2',
    subject: 'chemistry',
    chapter: 'chemical-bonding',
    topic: 'Covalent Bonding',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which of the following molecules has a double covalent bond?',
    options: ['O₂', 'H₂', 'Cl₂', 'HCl'],
    correctAnswer: 'O₂',
    explanation: 'Oxygen (O₂) has a double covalent bond (O=O). Each oxygen atom shares 2 electrons to complete its octet.',
  },
  {
    id: 'chem-acid-1',
    subject: 'chemistry',
    chapter: 'acids-bases',
    topic: 'Properties',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which of the following is a strong acid?',
    options: ['HCl', 'CH₃COOH', 'H₂CO₃', 'H₂SO₃'],
    correctAnswer: 'HCl',
    explanation: 'HCl (hydrochloric acid) is a strong acid that completely dissociates in water. CH₃COOH (acetic acid), H₂CO₃ (carbonic acid), and H₂SO₃ (sulphurous acid) are all weak acids.',
  },
  {
    id: 'chem-acid-2',
    subject: 'chemistry',
    chapter: 'acids-bases',
    topic: 'pH Scale',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'What is the pH of a neutral solution? How does pH change when a base is added to water?',
    correctAnswer: 'A neutral solution has pH = 7. When a base is added to water, the pH increases above 7.',
    explanation: 'pH scale ranges from 0-14. pH < 7 is acidic, pH = 7 is neutral, pH > 7 is basic/alkaline.',
  },
  {
    id: 'chem-mole-1',
    subject: 'chemistry',
    chapter: 'mole-concept',
    topic: 'Mole Calculations',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Calculate the number of moles in 44 g of CO₂. (Atomic masses: C = 12, O = 16)',
    correctAnswer: '1 mole',
    explanation: 'Molar mass of CO₂ = 12 + 2(16) = 44 g/mol. Number of moles = mass/molar mass = 44/44 = 1 mole.',
    commonErrors: ['Incorrectly calculating molar mass', 'Forgetting to multiply atomic mass of O by 2'],
  },
  {
    id: 'chem-mole-2',
    subject: 'chemistry',
    chapter: 'mole-concept',
    topic: 'Stoichiometry',
    type: 'numerical',
    difficulty: 'hard',
    marks: 4,
    question: 'How many grams of hydrogen are produced when 46 g of sodium reacts with water?\n2Na + 2H₂O → 2NaOH + H₂\n(Atomic masses: Na = 23, H = 1)',
    correctAnswer: '2 g',
    explanation: '46 g Na = 46/23 = 2 moles Na. From the equation, 2 moles Na produce 1 mole H₂. 1 mole H₂ = 2 g.',
    commonErrors: ['Not balancing the equation first', 'Incorrect mole ratio from equation'],
    markScheme: '1 mark for moles of Na, 1 mark for mole ratio, 1 mark for mass of H₂, 1 mark for units',
  },
  {
    id: 'chem-elec-1',
    subject: 'chemistry',
    chapter: 'electrolysis',
    topic: 'Electrolyte Types',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Which of the following is a strong electrolyte?',
    options: ['NaCl solution', 'Sugar solution', 'Alcohol', 'Distilled water'],
    correctAnswer: 'NaCl solution',
    explanation: 'NaCl completely dissociates in water to form Na⁺ and Cl⁻ ions, making it a strong electrolyte. Sugar, alcohol, and distilled water do not form ions.',
  },
  {
    id: 'chem-elec-2',
    subject: 'chemistry',
    chapter: 'electrolysis',
    topic: 'Electrode Reactions',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'During electrolysis of acidified water, write the reaction at the (a) cathode, and (b) anode. Which gas is collected at each electrode?',
    correctAnswer: '(a) Cathode: 2H⁺ + 2e⁻ → H₂ (Hydrogen gas collected). (b) Anode: 4OH⁻ → 2H₂O + O₂ + 4e⁻ (Oxygen gas collected).',
    explanation: 'At the cathode (reduction), hydrogen ions gain electrons. At the anode (oxidation), hydroxide ions lose electrons.',
    commonErrors: ['Swapping cathode and anode reactions', 'Forgetting that cathode = reduction, anode = oxidation'],
  },
  {
    id: 'chem-metal-1',
    subject: 'chemistry',
    chapter: 'metallurgy',
    topic: 'Extraction Methods',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Name the process used to extract: (a) Sodium, (b) Iron, (c) Gold. Give reasons for the method chosen.',
    correctAnswer: '(a) Sodium - Electrolytic reduction (very reactive metal). (b) Iron - Reduction with carbon/coke in blast furnace (moderately reactive). (c) Gold - Found in native/free state (least reactive).',
    explanation: 'The method of extraction depends on the reactivity of the metal. More reactive metals need electrolysis, moderately reactive use carbon reduction, least reactive are found free.',
  },
  {
    id: 'chem-org-1',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'Homologous Series',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The general formula of alkenes is:',
    options: ['CₙH₂ₙ', 'CₙH₂ₙ₊₂', 'CₙH₂ₙ₋₂', 'CₙHₙ'],
    correctAnswer: 'CₙH₂ₙ',
    explanation: 'Alkenes have the general formula CₙH₂ₙ. They contain one C=C double bond. Alkanes are CₙH₂ₙ₊₂ and alkynes are CₙH₂ₙ₋₂.',
  },
  {
    id: 'chem-org-2',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'Functional Groups',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Name the functional group and the homologous series for: (a) CH₃OH, (b) CH₃COOH.',
    correctAnswer: '(a) -OH (hydroxyl group), Alcohols. (b) -COOH (carboxyl group), Carboxylic acids.',
    explanation: 'Functional groups determine the chemical properties of organic compounds.',
  },
  {
    id: 'chem-org-3',
    subject: 'chemistry',
    chapter: 'organic-chemistry',
    topic: 'IUPAC Naming',
    type: 'numerical',
    difficulty: 'medium',
    marks: 2,
    question: 'Give the IUPAC name of: CH₃-CH₂-CH₂-OH',
    correctAnswer: 'Propan-1-ol',
    explanation: '3 carbon chain (prop-) with -OH group on carbon 1. IUPAC name: Propan-1-ol.',
    commonErrors: ['Writing 1-propanol instead of propan-1-ol', 'Numbering from wrong end of chain'],
  },
];
