import { Question } from '@/types';

export const englishQuestions: Question[] = [
  {
    id: 'eng-gram-1',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Tenses',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct form: "She _____ to school every day."',
    options: ['goes', 'go', 'going', 'gone'],
    correctAnswer: 'goes',
    explanation: 'Simple present tense with third person singular subject (she) requires "goes".',
  },
  {
    id: 'eng-gram-2',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Active/Passive Voice',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Change to passive voice: "The teacher praised the students."',
    correctAnswer: 'The students were praised by the teacher.',
    explanation: 'Passive voice: Object + was/were + past participle + by + subject. "Students" becomes the subject, "teacher" becomes the agent.',
    commonErrors: ['Using "was" instead of "were" with plural subject', 'Forgetting "by the teacher"'],
  },
  {
    id: 'eng-gram-3',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Direct/Indirect Speech',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Change to indirect speech: He said, "I am going to the market."',
    correctAnswer: 'He said that he was going to the market.',
    explanation: 'In indirect speech: "I" changes to "he", "am going" changes to "was going" (present continuous → past continuous), quotation marks removed, "that" added.',
    commonErrors: ['Not changing the tense', 'Not changing the pronoun'],
  },
  {
    id: 'eng-gram-4',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Prepositions',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct preposition: "The book is _____ the table."',
    options: ['on', 'in', 'at', 'by'],
    correctAnswer: 'on',
    explanation: '"On" is used when something is on a surface. "In" is for enclosed spaces, "at" for specific points.',
  },
  {
    id: 'eng-gram-5',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Tenses',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Fill in the blanks with the correct tense of the verb given in brackets:\n(a) She _____ (complete) her homework before dinner yesterday.\n(b) They _____ (play) cricket since morning.',
    correctAnswer: '(a) had completed (past perfect). (b) have been playing (present perfect continuous).',
    explanation: '(a) Past perfect is used for an action completed before another past action. (b) Present perfect continuous is used for an action that started in the past and is still continuing.',
  },
  {
    id: 'eng-gram-6',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Conjunctions',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct conjunction: "Study hard _____ you will fail."',
    options: ['or', 'and', 'but', 'so'],
    correctAnswer: 'or',
    explanation: '"Or" is used to present an alternative/consequence. "Study hard or you will fail" implies a warning/conditional.',
  },
  {
    id: 'eng-comp-1',
    subject: 'english',
    chapter: 'comprehension',
    topic: 'Passage Analysis',
    type: 'long_answer',
    difficulty: 'medium',
    marks: 4,
    question: 'Read the passage and answer:\n\n"The rainforest is home to more than half of the world\'s plant and animal species. Despite covering only 6% of the Earth\'s surface, these forests are being destroyed at an alarming rate. Every minute, an area equivalent to 20 football fields is lost. This deforestation contributes to climate change, loss of biodiversity, and disruption of water cycles."\n\n(a) What fraction of Earth\'s surface do rainforests cover?\n(b) Why is deforestation harmful? Give two reasons from the passage.\n(c) Find a word from the passage that means "variety of living organisms."',
    correctAnswer: '(a) 6% of the Earth\'s surface. (b) Two reasons: (i) contributes to climate change, (ii) loss of biodiversity / disruption of water cycles. (c) Biodiversity.',
    explanation: 'Comprehension questions test the ability to extract information, infer meaning, and understand vocabulary in context.',
    markScheme: '1 mark for (a), 2 marks for (b) - 1 mark per reason, 1 mark for (c)',
  },
  {
    id: 'eng-comp-2',
    subject: 'english',
    chapter: 'composition',
    topic: 'Letter Writing',
    type: 'long_answer',
    difficulty: 'medium',
    marks: 5,
    question: 'Write a letter to the editor of a newspaper about the problem of water scarcity in your locality. Include: (a) the current situation, (b) causes, (c) suggestions to solve the problem.',
    correctAnswer: 'A formal letter format with: sender\'s address, date, editor\'s address, subject line, body covering the three points, formal closing. Key elements: clear description of water shortage, causes like wastage/poor infrastructure/population growth, solutions like rainwater harvesting/fixing leaks/awareness campaigns.',
    explanation: 'ICSE formal letters must follow proper format: address, date, salutation, subject, body in paragraphs, closing.',
    markScheme: '1 mark for format, 1 mark for each content point (situation, causes, suggestions), 1 mark for language and expression',
    commonErrors: ['Missing sender address or date', 'Informal tone in a formal letter', 'Not addressing all three points asked'],
  },
  {
    id: 'eng-gram-7',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Active/Passive Voice',
    type: 'short_answer',
    difficulty: 'hard',
    marks: 2,
    question: 'Change to passive voice: "Who broke the window?"',
    correctAnswer: 'By whom was the window broken?',
    explanation: 'Interrogative sentences in passive voice: "Who" changes to "By whom", and the rest follows passive structure.',
    commonErrors: ['Writing "Who was the window broken by?"', 'Not changing "who" to "by whom"'],
  },
];
