import { Question } from '@/types';

export const englishQuestions: Question[] = [
  {
    id: 'eng-gram-1',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Tenses',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct form: "She _____ to school every day."',
    options: ['goes', 'go', 'going', 'gone'],
    correctAnswer: 'goes',
    explanation: 'Simple present tense with third person singular subject (she) requires "goes".',
  },
  {
    id: 'eng-gram-2',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Active/Passive Voice',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Change to passive voice: "The teacher praised the students."',
    correctAnswer: 'The students were praised by the teacher.',
    explanation: 'Passive voice: Object + was/were + past participle + by + subject. "Students" becomes the subject, "teacher" becomes the agent.',
    commonErrors: ['Using "was" instead of "were" with plural subject', 'Forgetting "by the teacher"'],
  },
  {
    id: 'eng-gram-3',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Direct/Indirect Speech',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Change to indirect speech: He said, "I am going to the market."',
    correctAnswer: 'He said that he was going to the market.',
    explanation: 'In indirect speech: "I" changes to "he", "am going" changes to "was going" (present continuous → past continuous), quotation marks removed, "that" added.',
    commonErrors: ['Not changing the tense', 'Not changing the pronoun'],
  },
  {
    id: 'eng-gram-4',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Prepositions',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct preposition: "The book is _____ the table."',
    options: ['on', 'in', 'at', 'by'],
    correctAnswer: 'on',
    explanation: '"On" is used when something is on a surface. "In" is for enclosed spaces, "at" for specific points.',
  },
  {
    id: 'eng-gram-5',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Tenses',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Fill in the blanks with the correct tense of the verb given in brackets:\n(a) She _____ (complete) her homework before dinner yesterday.\n(b) They _____ (play) cricket since morning.',
    correctAnswer: '(a) had completed (past perfect). (b) have been playing (present perfect continuous).',
    explanation: '(a) Past perfect is used for an action completed before another past action. (b) Present perfect continuous is used for an action that started in the past and is still continuing.',
  },
  {
    id: 'eng-gram-6',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Conjunctions',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct conjunction: "Study hard _____ you will fail."',
    options: ['or', 'and', 'but', 'so'],
    correctAnswer: 'or',
    explanation: '"Or" is used to present an alternative/consequence. "Study hard or you will fail" implies a warning/conditional.',
  },
  {
    id: 'eng-comp-1',
    subject: 'english',
    chapter: 'comprehension',
    topic: 'Passage Analysis',
    type: 'long_answer',
    difficulty: 'medium',
    marks: 4,
    question: 'Read the passage and answer:\n\n"The rainforest is home to more than half of the world\'s plant and animal species. Despite covering only 6% of the Earth\'s surface, these forests are being destroyed at an alarming rate. Every minute, an area equivalent to 20 football fields is lost. This deforestation contributes to climate change, loss of biodiversity, and disruption of water cycles."\n\n(a) What fraction of Earth\'s surface do rainforests cover?\n(b) Why is deforestation harmful? Give two reasons from the passage.\n(c) Find a word from the passage that means "variety of living organisms."',
    correctAnswer: '(a) 6% of the Earth\'s surface. (b) Two reasons: (i) contributes to climate change, (ii) loss of biodiversity / disruption of water cycles. (c) Biodiversity.',
    explanation: 'Comprehension questions test the ability to extract information, infer meaning, and understand vocabulary in context.',
    markScheme: '1 mark for (a), 2 marks for (b) - 1 mark per reason, 1 mark for (c)',
  },
  {
    id: 'eng-comp-2',
    subject: 'english',
    chapter: 'composition',
    topic: 'Letter Writing',
    type: 'long_answer',
    difficulty: 'medium',
    marks: 5,
    question: 'Write a letter to the editor of a newspaper about the problem of water scarcity in your locality. Include: (a) the current situation, (b) causes, (c) suggestions to solve the problem.',
    correctAnswer: 'A formal letter format with: sender\'s address, date, editor\'s address, subject line, body covering the three points, formal closing. Key elements: clear description of water shortage, causes like wastage/poor infrastructure/population growth, solutions like rainwater harvesting/fixing leaks/awareness campaigns.',
    explanation: 'ICSE formal letters must follow proper format: address, date, salutation, subject, body in paragraphs, closing.',
    markScheme: '1 mark for format, 1 mark for each content point (situation, causes, suggestions), 1 mark for language and expression',
    commonErrors: ['Missing sender address or date', 'Informal tone in a formal letter', 'Not addressing all three points asked'],
  },
  {
    id: 'eng-gram-7',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Active/Passive Voice',
    type: 'short_answer',
    difficulty: 'hard',
    marks: 2,
    question: 'Change to passive voice: "Who broke the window?"',
    correctAnswer: 'By whom was the window broken?',
    explanation: 'Interrogative sentences in passive voice: "Who" changes to "By whom", and the rest follows passive structure.',
    commonErrors: ['Writing "Who was the window broken by?"', 'Not changing "who" to "by whom"'],
  },
  {
    id: 'eng-gram-8',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Direct/Indirect Speech',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Change to indirect speech: She said to me, "Please lend me your book."',
    correctAnswer: 'She requested me to lend her my book.',
    explanation: '"Please" indicates a request, so the reporting verb changes to "requested". Imperative sentences use "to + verb" in indirect speech.',
    commonErrors: ['Using "said" instead of "requested"', 'Not changing pronouns correctly'],
  },
  {
    id: 'eng-gram-9',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Sentence Transformation',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'Rewrite using "unless": "If you do not study hard, you will not pass."',
    correctAnswer: 'Unless you study hard, you will not pass.',
    explanation: '"Unless" means "if not". When converting, remove "not" from the if-clause. "If you do not study" becomes "Unless you study".',
    commonErrors: ['Keeping "not" after "unless" (double negative)', 'Changing the meaning of the sentence'],
  },
  {
    id: 'eng-gram-10',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Phrasal Verbs',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'Choose the correct meaning of "break out":',
    options: ['To start suddenly (as in war or fire)', 'To enter forcefully', 'To repair', 'To rest'],
    correctAnswer: 'To start suddenly (as in war or fire)',
    explanation: '"Break out" means to start suddenly. Example: "A fire broke out in the building." Other phrasal verbs with break: break down (stop working), break in (enter by force).',
  },
  {
    id: 'eng-gram-11',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Articles',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'Fill in the blanks with suitable articles:\n(a) He is _____ honest man.\n(b) _____ Ganga is a sacred river.',
    correctAnswer: '(a) an — "honest" begins with a vowel sound (the "h" is silent). (b) The — names of rivers take the definite article "the".',
    explanation: 'Articles depend on sound, not spelling. "An" before vowel sounds; "The" with unique/specific nouns, rivers, mountain ranges, etc.',
    commonErrors: ['Using "a" before "honest" (h is silent)', 'Omitting "the" before river names'],
  },
  {
    id: 'eng-comp-3',
    subject: 'english',
    chapter: 'comprehension',
    topic: 'Passage Analysis',
    type: 'long_answer',
    difficulty: 'medium',
    marks: 4,
    question: 'Read the passage and answer:\n\n"Education is not merely about acquiring knowledge from textbooks. It is about developing character, values, and the ability to think critically. A truly educated person is one who can apply knowledge to real-life situations and contribute positively to society. As Nelson Mandela said, \'Education is the most powerful weapon which you can use to change the world.\'"\n\n(a) According to the passage, what is education about?\n(b) What makes a person truly educated?\n(c) Explain the quote by Nelson Mandela in your own words.\n(d) Find a word that means "obtaining or gaining."',
    correctAnswer: '(a) Education is about developing character, values, and critical thinking, not just textbook knowledge. (b) A person who can apply knowledge to real-life situations and contribute positively to society. (c) Education empowers people to bring about change and improve the world. (d) Acquiring.',
    explanation: 'This tests comprehension, inference, interpretation, and vocabulary skills.',
    markScheme: '1 mark for each part',
  },
  {
    id: 'eng-comp-4',
    subject: 'english',
    chapter: 'composition',
    topic: 'Notice Writing',
    type: 'long_answer',
    difficulty: 'medium',
    marks: 4,
    question: 'You are the Head Boy/Head Girl of your school. Write a notice informing students about an inter-school debate competition.',
    correctAnswer: 'A formal notice with: Name of institution at top, "NOTICE" heading, date, title, body (details of the debate — topic, date, time, venue, eligibility, registration deadline, contact person), signature with name and designation.',
    explanation: 'ICSE notices must follow formal format with proper headings and complete information.',
    markScheme: '1 mark for format (heading, date, signature), 1 mark for title, 1 mark for complete details, 1 mark for language and clarity',
    commonErrors: ['Missing date or signature', 'Informal language', 'Incomplete details about the event'],
  },
  {
    id: 'eng-gram-12',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Subject-Verb Agreement',
    type: 'mcq',
    difficulty: 'medium',
    marks: 1,
    question: 'Choose the correct option: "Each of the students _____ given a certificate."',
    options: ['was', 'were', 'are', 'have been'],
    correctAnswer: 'was',
    explanation: '"Each" is singular and takes a singular verb. "Each of the students" treats each student individually, so "was" is correct.',
  },
  {
    id: 'eng-gram-13',
    subject: 'english',
    chapter: 'grammar',
    topic: 'Conditional Sentences',
    type: 'short_answer',
    difficulty: 'hard',
    marks: 2,
    question: 'Complete: "If I _____ (be) the Prime Minister, I _____ (improve) the education system."',
    correctAnswer: 'If I were the Prime Minister, I would improve the education system.',
    explanation: 'This is an unreal/hypothetical condition (Type 2 conditional). Use "were" for all subjects in the if-clause and "would + base form" in the main clause.',
    commonErrors: ['Using "was" instead of "were"', 'Using "will" instead of "would" in the main clause'],
  },
];
