import { Question } from '@/types';

export const historyQuestions: Question[] = [
  {
    id: 'hist-if-1',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Early Nationalism',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Indian National Congress was founded in the year:',
    options: ['1885', '1857', '1905', '1919'],
    correctAnswer: '1885',
    explanation: 'The Indian National Congress was founded in 1885 by A.O. Hume in Bombay. W.C. Bonnerjee was its first president.',
  },
  {
    id: 'hist-if-2',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Gandhian Era',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What was the Salt March (Dandi March)? Why was it significant?',
    correctAnswer: 'The Salt March (1930) was a 388 km march from Sabarmati Ashram to Dandi led by Mahatma Gandhi to protest the British salt tax. Gandhi and followers made salt from seawater, breaking the Salt Act. It was significant because: (1) it was an act of civil disobedience against an unjust law, (2) it gained worldwide attention, (3) it united Indians across classes in the freedom struggle.',
    explanation: 'The Salt March was part of the Civil Disobedience Movement and demonstrated the power of non-violent protest.',
    commonErrors: ['Incorrect distance or starting point', 'Not explaining why salt tax was chosen as the issue'],
  },
  {
    id: 'hist-if-3',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Independence',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Quit India Movement was launched in:',
    options: ['1942', '1940', '1944', '1946'],
    correctAnswer: '1942',
    explanation: 'The Quit India Movement (Bharat Chhodo Andolan) was launched on 8 August 1942 by Mahatma Gandhi at the Bombay session of the All-India Congress Committee.',
  },
  {
    id: 'hist-ww-1',
    subject: 'history',
    chapter: 'world-wars',
    topic: 'Causes',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'State three causes of World War I.',
    correctAnswer: '1. Militarism: European powers were building up their armies and navies. 2. Alliance System: Europe was divided into two hostile alliances (Triple Alliance and Triple Entente). 3. Imperialism: Competition for colonies and resources created tensions. (Other valid causes: nationalism, assassination of Archduke Franz Ferdinand)',
    explanation: 'The main causes are often remembered as MAIN: Militarism, Alliance system, Imperialism, Nationalism.',
  },
  {
    id: 'hist-ww-2',
    subject: 'history',
    chapter: 'world-wars',
    topic: 'Consequences',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What were the consequences of World War II?',
    correctAnswer: '1. Formation of the United Nations (1945) to maintain world peace. 2. Division of Germany into East and West Germany. 3. Beginning of the Cold War between USA and USSR. 4. Decolonisation - many Asian and African countries gained independence. 5. Use of atomic bombs on Hiroshima and Nagasaki.',
    explanation: 'WWII fundamentally changed the world order, ending European dominance and establishing the USA and USSR as superpowers.',
  },
  {
    id: 'hist-un-1',
    subject: 'history',
    chapter: 'united-nations',
    topic: 'Organs',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'How many permanent members are there in the UN Security Council?',
    options: ['5', '10', '15', '7'],
    correctAnswer: '5',
    explanation: 'The 5 permanent members (P5) are: USA, UK, France, Russia, and China. They have veto power.',
  },
  {
    id: 'hist-un-2',
    subject: 'history',
    chapter: 'united-nations',
    topic: 'Agencies',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'Name any two specialized agencies of the United Nations and their functions.',
    correctAnswer: '1. WHO (World Health Organization) - Works for international public health, disease prevention, and health research. 2. UNESCO (United Nations Educational, Scientific and Cultural Organization) - Promotes education, science, and cultural preservation worldwide.',
    explanation: 'The UN has many specialized agencies, each focusing on specific global issues.',
  },
  {
    id: 'hist-con-1',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Fundamental Rights',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'List any three Fundamental Rights guaranteed by the Indian Constitution.',
    correctAnswer: '1. Right to Equality (Articles 14-18): Equal treatment before law, prohibition of discrimination. 2. Right to Freedom (Articles 19-22): Freedom of speech, assembly, movement, etc. 3. Right against Exploitation (Articles 23-24): Prohibition of human trafficking and child labour.',
    explanation: 'There are 6 Fundamental Rights in the Indian Constitution (Right to Property was removed by the 44th Amendment).',
    commonErrors: ['Including Right to Property (no longer a fundamental right)', 'Confusing Fundamental Rights with Directive Principles'],
  },
  {
    id: 'hist-con-2',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Parliament',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Upper House of the Indian Parliament is called:',
    options: ['Rajya Sabha', 'Lok Sabha', 'Vidhan Sabha', 'Vidhan Parishad'],
    correctAnswer: 'Rajya Sabha',
    explanation: 'Rajya Sabha (Council of States) is the Upper House. Lok Sabha (House of the People) is the Lower House. Vidhan Sabha and Vidhan Parishad are state legislatures.',
  },
  {
    id: 'hist-con-3',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Judiciary',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'What is meant by "Judicial Review"? Why is it important?',
    correctAnswer: 'Judicial Review is the power of the judiciary to examine the constitutionality of legislative enactments and executive orders. If a law is found to violate the Constitution, the court can declare it null and void. It is important because it protects Fundamental Rights and maintains the supremacy of the Constitution.',
    explanation: 'Judicial Review is a key feature of the Indian Constitution that ensures checks and balances between the three branches of government.',
  },
];
