import { Question } from '@/types';

export const historyQuestions: Question[] = [
  {
    id: 'hist-if-1',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Early Nationalism',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Indian National Congress was founded in the year:',
    options: ['1885', '1857', '1905', '1919'],
    correctAnswer: '1885',
    explanation: 'The Indian National Congress was founded in 1885 by A.O. Hume in Bombay. W.C. Bonnerjee was its first president.',
  },
  {
    id: 'hist-if-2',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Gandhian Era',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What was the Salt March (Dandi March)? Why was it significant?',
    correctAnswer: 'The Salt March (1930) was a 388 km march from Sabarmati Ashram to Dandi led by Mahatma Gandhi to protest the British salt tax. Gandhi and followers made salt from seawater, breaking the Salt Act. It was significant because: (1) it was an act of civil disobedience against an unjust law, (2) it gained worldwide attention, (3) it united Indians across classes in the freedom struggle.',
    explanation: 'The Salt March was part of the Civil Disobedience Movement and demonstrated the power of non-violent protest.',
    commonErrors: ['Incorrect distance or starting point', 'Not explaining why salt tax was chosen as the issue'],
  },
  {
    id: 'hist-if-3',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Independence',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Quit India Movement was launched in:',
    options: ['1942', '1940', '1944', '1946'],
    correctAnswer: '1942',
    explanation: 'The Quit India Movement (Bharat Chhodo Andolan) was launched on 8 August 1942 by Mahatma Gandhi at the Bombay session of the All-India Congress Committee.',
  },
  {
    id: 'hist-ww-1',
    subject: 'history',
    chapter: 'world-wars',
    topic: 'Causes',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'State three causes of World War I.',
    correctAnswer: '1. Militarism: European powers were building up their armies and navies. 2. Alliance System: Europe was divided into two hostile alliances (Triple Alliance and Triple Entente). 3. Imperialism: Competition for colonies and resources created tensions. (Other valid causes: nationalism, assassination of Archduke Franz Ferdinand)',
    explanation: 'The main causes are often remembered as MAIN: Militarism, Alliance system, Imperialism, Nationalism.',
  },
  {
    id: 'hist-ww-2',
    subject: 'history',
    chapter: 'world-wars',
    topic: 'Consequences',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What were the consequences of World War II?',
    correctAnswer: '1. Formation of the United Nations (1945) to maintain world peace. 2. Division of Germany into East and West Germany. 3. Beginning of the Cold War between USA and USSR. 4. Decolonisation - many Asian and African countries gained independence. 5. Use of atomic bombs on Hiroshima and Nagasaki.',
    explanation: 'WWII fundamentally changed the world order, ending European dominance and establishing the USA and USSR as superpowers.',
  },
  {
    id: 'hist-un-1',
    subject: 'history',
    chapter: 'united-nations',
    topic: 'Organs',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'How many permanent members are there in the UN Security Council?',
    options: ['5', '10', '15', '7'],
    correctAnswer: '5',
    explanation: 'The 5 permanent members (P5) are: USA, UK, France, Russia, and China. They have veto power.',
  },
  {
    id: 'hist-un-2',
    subject: 'history',
    chapter: 'united-nations',
    topic: 'Agencies',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'Name any two specialized agencies of the United Nations and their functions.',
    correctAnswer: '1. WHO (World Health Organization) - Works for international public health, disease prevention, and health research. 2. UNESCO (United Nations Educational, Scientific and Cultural Organization) - Promotes education, science, and cultural preservation worldwide.',
    explanation: 'The UN has many specialized agencies, each focusing on specific global issues.',
  },
  {
    id: 'hist-con-1',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Fundamental Rights',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'List any three Fundamental Rights guaranteed by the Indian Constitution.',
    correctAnswer: '1. Right to Equality (Articles 14-18): Equal treatment before law, prohibition of discrimination. 2. Right to Freedom (Articles 19-22): Freedom of speech, assembly, movement, etc. 3. Right against Exploitation (Articles 23-24): Prohibition of human trafficking and child labour.',
    explanation: 'There are 6 Fundamental Rights in the Indian Constitution (Right to Property was removed by the 44th Amendment).',
    commonErrors: ['Including Right to Property (no longer a fundamental right)', 'Confusing Fundamental Rights with Directive Principles'],
  },
  {
    id: 'hist-con-2',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Parliament',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Upper House of the Indian Parliament is called:',
    options: ['Rajya Sabha', 'Lok Sabha', 'Vidhan Sabha', 'Vidhan Parishad'],
    correctAnswer: 'Rajya Sabha',
    explanation: 'Rajya Sabha (Council of States) is the Upper House. Lok Sabha (House of the People) is the Lower House. Vidhan Sabha and Vidhan Parishad are state legislatures.',
  },
  {
    id: 'hist-con-3',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Judiciary',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 2,
    question: 'What is meant by "Judicial Review"? Why is it important?',
    correctAnswer: 'Judicial Review is the power of the judiciary to examine the constitutionality of legislative enactments and executive orders. If a law is found to violate the Constitution, the court can declare it null and void. It is important because it protects Fundamental Rights and maintains the supremacy of the Constitution.',
    explanation: 'Judicial Review is a key feature of the Indian Constitution that ensures checks and balances between the three branches of government.',
  },
  {
    id: 'hist-if-4',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Early Nationalism',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Distinguish between the Moderates and the Extremists in the Indian National Congress.',
    correctAnswer: 'Moderates (1885-1905): Led by Gokhale, Dadabhai Naoroji. Methods: petitions, prayers, constitutional means. Believed in British sense of justice. Extremists (1905 onwards): Led by Tilak, Lala Lajpat Rai, Bipin Chandra Pal (Lal-Bal-Pal). Methods: boycott, swadeshi, passive resistance. Believed in self-reliance and direct action.',
    explanation: 'The split between Moderates and Extremists occurred at the Surat Session (1907) of the INC.',
    commonErrors: ['Not naming key leaders', 'Confusing methods of the two groups'],
  },
  {
    id: 'hist-if-5',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Gandhian Era',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Non-Cooperation Movement was launched in:',
    options: ['1920', '1930', '1942', '1919'],
    correctAnswer: '1920',
    explanation: 'The Non-Cooperation Movement was launched in 1920 by Gandhi in response to the Jallianwala Bagh massacre (1919) and the Rowlatt Act. It was called off after the Chauri Chaura incident (1922).',
  },
  {
    id: 'hist-if-6',
    subject: 'history',
    chapter: 'indian-freedom',
    topic: 'Independence',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'What was the Mountbatten Plan? State its main provisions.',
    correctAnswer: 'The Mountbatten Plan (3 June 1947) was the plan for the partition and independence of India. Main provisions: (1) India to be divided into two dominions — India and Pakistan. (2) Princely states could join either dominion. (3) A boundary commission to demarcate borders. (4) Transfer of power on 15 August 1947.',
    explanation: 'Lord Mountbatten was the last Viceroy of India who oversaw the transfer of power.',
  },
  {
    id: 'hist-ww-3',
    subject: 'history',
    chapter: 'world-wars',
    topic: 'Key Events',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The Treaty of Versailles (1919) was signed after:',
    options: ['World War I', 'World War II', 'The Cold War', 'The French Revolution'],
    correctAnswer: 'World War I',
    explanation: 'The Treaty of Versailles (28 June 1919) ended WWI. It imposed harsh terms on Germany including war guilt, reparations, and territorial losses, which contributed to WWII.',
  },
  {
    id: 'hist-ww-4',
    subject: 'history',
    chapter: 'world-wars',
    topic: 'Causes',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'How did the rise of Nazism in Germany contribute to World War II?',
    correctAnswer: 'Hitler and the Nazi Party rose to power in 1933 exploiting economic crisis and national humiliation from the Treaty of Versailles. Nazism contributed to WWII through: (1) Aggressive expansionism — annexation of Austria, Sudetenland. (2) Violation of Treaty of Versailles — rearmament. (3) Ideology of racial supremacy and lebensraum (living space). (4) Invasion of Poland (1 Sept 1939) directly triggered WWII.',
    explanation: 'The policy of appeasement by Britain and France allowed Hitler to expand unchecked until the invasion of Poland.',
  },
  {
    id: 'hist-un-3',
    subject: 'history',
    chapter: 'united-nations',
    topic: 'General Assembly',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'State two functions of the UN General Assembly.',
    correctAnswer: '1. Discusses and makes recommendations on matters of international peace and security. 2. Approves the UN budget and apportions contributions among member states. (Also valid: elects non-permanent members of Security Council, appoints Secretary-General on recommendation of Security Council.)',
    explanation: 'The General Assembly is the main deliberative organ where all 193 member states have equal representation (one vote each).',
  },
  {
    id: 'hist-con-4',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Directive Principles',
    type: 'mcq',
    difficulty: 'medium',
    marks: 1,
    question: 'Directive Principles of State Policy are:',
    options: ['Non-justiciable (not enforceable by court)', 'Enforceable by Supreme Court', 'Part of Fundamental Rights', 'Applicable only to states'],
    correctAnswer: 'Non-justiciable (not enforceable by court)',
    explanation: 'Directive Principles (Part IV, Articles 36-51) are guidelines for the government in policy-making but cannot be enforced by courts, unlike Fundamental Rights.',
  },
  {
    id: 'hist-con-5',
    subject: 'history',
    chapter: 'indian-constitution',
    topic: 'Parliament',
    type: 'short_answer',
    difficulty: 'medium',
    marks: 3,
    question: 'Explain the procedure of passing a Money Bill in the Indian Parliament.',
    correctAnswer: 'A Money Bill can only be introduced in Lok Sabha, not Rajya Sabha. After passing in Lok Sabha, it is sent to Rajya Sabha which must return it within 14 days with or without recommendations. Lok Sabha may accept or reject those recommendations. If not returned in 14 days, it is deemed passed. The President cannot return a Money Bill (no veto).',
    explanation: 'Money Bills deal with taxation, government spending, borrowing, etc. Rajya Sabha has limited power over Money Bills.',
    commonErrors: ['Saying Money Bill can be introduced in either house', 'Not mentioning the 14-day time limit'],
  },
];
