import { Question } from '@/types';

export const mathematicsQuestions: Question[] = [
  {
    id: 'math-qe-1',
    subject: 'mathematics',
    chapter: 'quadratic-equations',
    topic: 'Factorisation',
    type: 'numerical',
    difficulty: 'easy',
    marks: 3,
    question: 'Solve by factorisation: x² - 7x + 12 = 0',
    correctAnswer: 'x = 3, x = 4',
    explanation: 'x² - 7x + 12 = (x - 3)(x - 4) = 0. So x = 3 or x = 4.',
    commonErrors: ['Incorrect signs: writing (x + 3)(x + 4)', 'Finding factors of 12 that add to 7 but using wrong signs'],
    markScheme: '1 mark for correct factorisation, 1 mark for each root',
  },
  {
    id: 'math-qe-2',
    subject: 'mathematics',
    chapter: 'quadratic-equations',
    topic: 'Quadratic Formula',
    type: 'numerical',
    difficulty: 'medium',
    marks: 4,
    question: 'Using the quadratic formula, solve: 2x² + 5x - 3 = 0',
    correctAnswer: 'x = 1/2, x = -3',
    explanation: 'Using x = (-b ± √(b²-4ac))/2a: x = (-5 ± √(25+24))/4 = (-5 ± 7)/4. So x = 2/4 = 1/2 or x = -12/4 = -3.',
    commonErrors: ['Arithmetic error in discriminant calculation', 'Forgetting to divide by 2a'],
    markScheme: '1 mark for formula, 1 mark for discriminant, 1 mark for each root',
  },
  {
    id: 'math-qe-3',
    subject: 'mathematics',
    chapter: 'quadratic-equations',
    topic: 'Nature of Roots',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The discriminant of the equation x² - 4x + 4 = 0 is:',
    options: ['0', '4', '8', '-4'],
    correctAnswer: '0',
    explanation: 'D = b² - 4ac = (-4)² - 4(1)(4) = 16 - 16 = 0. Equal roots.',
  },
  {
    id: 'math-ap-1',
    subject: 'mathematics',
    chapter: 'ap-gp',
    topic: 'Arithmetic Progression',
    type: 'numerical',
    difficulty: 'easy',
    marks: 3,
    question: 'Find the 20th term of the AP: 3, 7, 11, 15, ...',
    correctAnswer: '79',
    explanation: 'a = 3, d = 4. T₂₀ = a + (n-1)d = 3 + 19(4) = 3 + 76 = 79.',
    commonErrors: ['Using n instead of (n-1)', 'Incorrect common difference'],
  },
  {
    id: 'math-ap-2',
    subject: 'mathematics',
    chapter: 'ap-gp',
    topic: 'Sum of Series',
    type: 'numerical',
    difficulty: 'medium',
    marks: 4,
    question: 'Find the sum of the first 15 terms of the AP: 5, 11, 17, 23, ...',
    correctAnswer: '705',
    explanation: 'a = 5, d = 6, n = 15. S₁₅ = n/2[2a + (n-1)d] = 15/2[10 + 84] = 15/2 × 94 = 705.',
    commonErrors: ['Using wrong formula', 'Arithmetic errors in multiplication'],
  },
  {
    id: 'math-cg-1',
    subject: 'mathematics',
    chapter: 'coordinate-geometry',
    topic: 'Section Formula',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Find the coordinates of the point that divides the line segment joining A(2, 3) and B(8, 9) in the ratio 2:1.',
    correctAnswer: '(6, 7)',
    explanation: 'x = (2×8 + 1×2)/(2+1) = 18/3 = 6. y = (2×9 + 1×3)/(2+1) = 21/3 = 7. Point is (6, 7).',
    commonErrors: ['Swapping m and n in the formula', 'Arithmetic errors'],
  },
  {
    id: 'math-cg-2',
    subject: 'mathematics',
    chapter: 'coordinate-geometry',
    topic: 'Slope',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The slope of the line passing through (2, 5) and (4, 11) is:',
    options: ['3', '2', '6', '1/3'],
    correctAnswer: '3',
    explanation: 'Slope = (y₂-y₁)/(x₂-x₁) = (11-5)/(4-2) = 6/2 = 3.',
  },
  {
    id: 'math-trig-1',
    subject: 'mathematics',
    chapter: 'trigonometry',
    topic: 'Identities',
    type: 'numerical',
    difficulty: 'medium',
    marks: 4,
    question: 'Prove that: (sin θ)/(1 - cos θ) + (1 - cos θ)/(sin θ) = 2 cosec θ',
    correctAnswer: '2 cosec θ',
    explanation: 'LHS = (sin²θ + (1-cosθ)²) / (sinθ(1-cosθ)) = (sin²θ + 1 - 2cosθ + cos²θ) / (sinθ(1-cosθ)) = (2 - 2cosθ) / (sinθ(1-cosθ)) = 2(1-cosθ) / (sinθ(1-cosθ)) = 2/sinθ = 2 cosec θ = RHS.',
    markScheme: '1 mark for taking LCM, 2 marks for simplification, 1 mark for final answer',
  },
  {
    id: 'math-trig-2',
    subject: 'mathematics',
    chapter: 'trigonometry',
    topic: 'Heights and Distances',
    type: 'numerical',
    difficulty: 'hard',
    marks: 4,
    question: 'From the top of a tower 60 m high, the angle of depression of the top and bottom of a building are 30° and 60° respectively. Find the height of the building.',
    correctAnswer: '40 m',
    explanation: 'Let h = height of building. Tower = 60m. For bottom: tan 60° = 60/d, so d = 60/√3 = 20√3. For top: tan 30° = (60-h)/d, so 1/√3 = (60-h)/(20√3), giving 20 = 60-h, so h = 40m.',
    commonErrors: ['Confusing angle of elevation with depression', 'Using wrong trigonometric ratio'],
  },
  {
    id: 'math-men-1',
    subject: 'mathematics',
    chapter: 'mensuration',
    topic: 'Cylinder',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'A cylinder has radius 7 cm and height 10 cm. Find its total surface area. (Use π = 22/7)',
    correctAnswer: '748 cm²',
    explanation: 'TSA = 2πr(r + h) = 2 × 22/7 × 7 × (7 + 10) = 44 × 17 = 748 cm².',
    commonErrors: ['Using CSA formula instead of TSA', 'Forgetting to include both circular faces'],
  },
  {
    id: 'math-men-2',
    subject: 'mathematics',
    chapter: 'mensuration',
    topic: 'Combined Solids',
    type: 'numerical',
    difficulty: 'hard',
    marks: 4,
    question: 'A solid consists of a hemisphere of radius 7 cm mounted on a cone of same radius and height 24 cm. Find the volume of the solid. (Use π = 22/7)',
    correctAnswer: '1950.67 cm³',
    explanation: 'Volume of hemisphere = 2/3 πr³ = 2/3 × 22/7 × 343 = 718.67 cm³. Volume of cone = 1/3 πr²h = 1/3 × 22/7 × 49 × 24 = 1232 cm³. Total = 718.67 + 1232 = 1950.67 cm³.',
  },
  {
    id: 'math-stat-1',
    subject: 'mathematics',
    chapter: 'statistics',
    topic: 'Mean',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Find the mean of the following distribution using step-deviation method:\n\nClass: 0-10, 10-20, 20-30, 30-40, 40-50\nFrequency: 5, 8, 15, 12, 10',
    correctAnswer: '26',
    explanation: 'Assumed mean A = 25, h = 10. Σfᵢdᵢ = 5(-2) + 8(-1) + 15(0) + 12(1) + 10(2) = -10 - 8 + 0 + 12 + 20 = 14. Σfᵢ = 50. Mean = A + h(Σfᵢdᵢ/Σfᵢ) = 25 + 10(14/50) = 25 + 2.8 ≈ 27.8. Using direct method: Mean = (5×5 + 8×15 + 15×25 + 12×35 + 10×45)/50 = 1300/50 = 26.',
  },
  {
    id: 'math-stat-2',
    subject: 'mathematics',
    chapter: 'statistics',
    topic: 'Probability',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'A bag contains 3 red, 4 blue, and 5 green balls. One ball is drawn at random. The probability that it is not green is:',
    options: ['7/12', '5/12', '1/3', '2/3'],
    correctAnswer: '7/12',
    explanation: 'Total balls = 12. Not green = 3 + 4 = 7. P(not green) = 7/12.',
  },
  {
    id: 'math-mat-1',
    subject: 'mathematics',
    chapter: 'matrices',
    topic: 'Matrix Operations',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'If A = [2 3; 1 4] and B = [1 0; -1 2], find AB.',
    correctAnswer: '[-1 6; -3 8]',
    explanation: 'AB[1,1] = 2(1) + 3(-1) = -1. AB[1,2] = 2(0) + 3(2) = 6. AB[2,1] = 1(1) + 4(-1) = -3. AB[2,2] = 1(0) + 4(2) = 8. AB = [-1 6; -3 8].',
    commonErrors: ['Multiplying element-wise instead of row×column', 'Order of multiplication matters: AB ≠ BA'],
  },
  {
    id: 'math-circle-1',
    subject: 'mathematics',
    chapter: 'circles',
    topic: 'Tangent Properties',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'If two tangents are drawn to a circle from an external point, then:',
    options: [
      'They are equal in length',
      'They are perpendicular to each other',
      'They are parallel',
      'One is longer than the other',
    ],
    correctAnswer: 'They are equal in length',
    explanation: 'Tangents drawn from an external point to a circle are always equal in length. This is a fundamental theorem of circles.',
  },
];
