import { Question } from '@/types';

export const physicsQuestions: Question[] = [
  {
    id: 'phy-force-1',
    subject: 'physics',
    chapter: 'force',
    topic: 'Force',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The SI unit of force is:',
    options: ['Newton', 'Joule', 'Watt', 'Pascal'],
    correctAnswer: 'Newton',
    explanation: 'Force = mass × acceleration. SI unit = kg × m/s² = Newton (N).',
  },
  {
    id: 'phy-force-2',
    subject: 'physics',
    chapter: 'force',
    topic: 'Work',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'A force of 50 N is applied on a body and it moves through a distance of 10 m in the direction of the force. Calculate the work done.',
    correctAnswer: '500 J',
    explanation: 'Work = Force × Distance = 50 × 10 = 500 J.',
    commonErrors: ['Forgetting to check if force and displacement are in the same direction'],
  },
  {
    id: 'phy-force-3',
    subject: 'physics',
    chapter: 'force',
    topic: 'Machines',
    type: 'numerical',
    difficulty: 'medium',
    marks: 4,
    question: 'A lever of class 1 has its fulcrum at 40 cm from the load and 120 cm from the effort. If the effort applied is 20 N, calculate: (a) the mechanical advantage, (b) the load that can be lifted.',
    correctAnswer: 'MA = 3, Load = 60 N',
    explanation: 'MA = Effort arm / Load arm = 120/40 = 3. Load = MA × Effort = 3 × 20 = 60 N.',
    markScheme: '2 marks for MA calculation, 2 marks for load calculation',
  },
  {
    id: 'phy-force-4',
    subject: 'physics',
    chapter: 'force',
    topic: 'Energy',
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: 'The kinetic energy of a body of mass m moving with velocity v is:',
    options: ['½mv²', 'mv²', '½mv', 'mv'],
    correctAnswer: '½mv²',
    explanation: 'Kinetic energy = ½mv². This is a fundamental formula.',
  },
  {
    id: 'phy-light-1',
    subject: 'physics',
    chapter: 'light',
    topic: 'Refraction',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'A ray of light passes from air to glass (refractive index 1.5). If the angle of incidence is 30°, find the angle of refraction.',
    correctAnswer: '19.47° (approximately 19.5°)',
    explanation: "By Snell's law: n₁ sin i = n₂ sin r. 1 × sin 30° = 1.5 × sin r. sin r = 0.5/1.5 = 1/3 = 0.333. r = sin⁻¹(0.333) ≈ 19.47°.",
    commonErrors: ["Inverting Snell's law", 'Not knowing that refractive index of air = 1'],
  },
  {
    id: 'phy-light-2',
    subject: 'physics',
    chapter: 'light',
    topic: 'Total Internal Reflection',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: 'State two conditions necessary for total internal reflection to occur.',
    correctAnswer: '1. Light must travel from a denser to a rarer medium. 2. The angle of incidence must be greater than the critical angle.',
    explanation: 'Total internal reflection occurs when light travelling from a denser medium (like glass) to a rarer medium (like air) hits the surface at an angle greater than the critical angle.',
  },
  {
    id: 'phy-light-3',
    subject: 'physics',
    chapter: 'light',
    topic: 'Lenses',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'An object is placed 30 cm from a convex lens of focal length 20 cm. Find the position and nature of the image.',
    correctAnswer: 'v = 60 cm, real and inverted',
    explanation: '1/v - 1/u = 1/f. 1/v - 1/(-30) = 1/20. 1/v = 1/20 - 1/30 = (3-2)/60 = 1/60. v = 60 cm. Since v is positive, image is real and inverted.',
    commonErrors: ['Sign convention errors', 'Not applying correct sign to u'],
  },
  {
    id: 'phy-sound-1',
    subject: 'physics',
    chapter: 'sound',
    topic: 'Echo',
    type: 'numerical',
    difficulty: 'easy',
    marks: 2,
    question: 'The minimum distance required to hear an echo is (given speed of sound = 340 m/s):',
    correctAnswer: '17 m',
    explanation: 'For an echo, t ≥ 0.1 s. Distance = speed × time / 2 = 340 × 0.1 / 2 = 17 m.',
  },
  {
    id: 'phy-elec-1',
    subject: 'physics',
    chapter: 'electricity',
    topic: "Ohm's Law",
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'Three resistors of 2 Ω, 3 Ω, and 6 Ω are connected in parallel. Find the equivalent resistance.',
    correctAnswer: '1 Ω',
    explanation: '1/R = 1/2 + 1/3 + 1/6 = 3/6 + 2/6 + 1/6 = 6/6 = 1. R = 1 Ω.',
    commonErrors: ['Adding resistances directly (that is for series)', 'Forgetting to take reciprocal at the end'],
  },
  {
    id: 'phy-elec-2',
    subject: 'physics',
    chapter: 'electricity',
    topic: 'Electrical Energy',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'An electric heater rated 1000 W is used for 2 hours daily. Calculate the cost of electricity for 30 days if the rate is ₹5 per unit.',
    correctAnswer: '₹300',
    explanation: 'Energy = Power × Time = 1000 W × 2 h × 30 days = 60,000 Wh = 60 kWh = 60 units. Cost = 60 × 5 = ₹300.',
    commonErrors: ['Not converting W to kW', 'Confusing kWh with kW'],
  },
  {
    id: 'phy-elec-3',
    subject: 'physics',
    chapter: 'electricity',
    topic: "Ohm's Law",
    type: 'mcq',
    difficulty: 'easy',
    marks: 1,
    question: "According to Ohm's law, the current flowing through a conductor is:",
    options: [
      'Directly proportional to the potential difference across it',
      'Inversely proportional to the potential difference across it',
      'Independent of the potential difference',
      'Proportional to the square of the potential difference',
    ],
    correctAnswer: 'Directly proportional to the potential difference across it',
    explanation: "Ohm's law: V = IR, so I = V/R. Current is directly proportional to voltage when resistance is constant.",
  },
  {
    id: 'phy-em-1',
    subject: 'physics',
    chapter: 'electromagnetism',
    topic: 'Electromagnetic Induction',
    type: 'short_answer',
    difficulty: 'easy',
    marks: 2,
    question: "State Faraday's law of electromagnetic induction.",
    correctAnswer: 'Whenever the magnetic flux linked with a coil changes, an EMF is induced in the coil. The magnitude of the induced EMF is proportional to the rate of change of magnetic flux.',
    explanation: "Faraday's law is the fundamental principle behind generators and transformers.",
  },
  {
    id: 'phy-cal-1',
    subject: 'physics',
    chapter: 'calorimetry',
    topic: 'Specific Heat',
    type: 'numerical',
    difficulty: 'medium',
    marks: 4,
    question: 'How much heat is required to raise the temperature of 500 g of water from 20°C to 100°C? (Specific heat of water = 4.2 J/g°C)',
    correctAnswer: '168,000 J or 168 kJ',
    explanation: 'Q = mcΔT = 500 × 4.2 × (100 - 20) = 500 × 4.2 × 80 = 168,000 J = 168 kJ.',
    commonErrors: ['Forgetting to convert grams to kg if using SI units', 'Using wrong temperature difference'],
  },
  {
    id: 'phy-radio-1',
    subject: 'physics',
    chapter: 'radioactivity',
    topic: 'Half-life',
    type: 'numerical',
    difficulty: 'medium',
    marks: 3,
    question: 'A radioactive element has a half-life of 5 years. What fraction of the element remains after 20 years?',
    correctAnswer: '1/16',
    explanation: 'Number of half-lives = 20/5 = 4. Fraction remaining = (1/2)⁴ = 1/16.',
    commonErrors: ['Dividing by 2 once instead of raising to power', 'Confusing half-life with decay constant'],
  },
];
