"""
Best-effort sector / industry classification for the NIFTY F&O symbol universe.

This is filled in from general knowledge of NSE-listed companies, NOT pulled
from an official NSE sector master file. It is good enough for exploratory
clustering / sector-strength ranking, but a handful of recently-listed or
demerged names are genuine guesses (flagged below with a comment) and should
be double-checked before this is used for real trading decisions.

Structure: symbol -> (sector, industry)
  - "sector" is a broad bucket (used for sector-rotation views)
  - "industry" is a finer-grained tag (used for sub-clustering)

Index symbols (NIFTY, BANKNIFTY, CNXMIDCAP, NIFTYFINSERVICE) are listed
separately in INDEX_SYMBOLS - they are benchmarks, not constituents, and are
handled as reference nodes in the relationship graph rather than as members
of a sector.
"""

INDEX_SYMBOLS = {
    "NIFTY": "Nifty 50",
    "BANKNIFTY": "Nifty Bank",
    "CNXMIDCAP": "Nifty Midcap",
    "NIFTYFINSERVICE": "Nifty Financial Services",
}

# sector -> industry
SYMBOL_SECTOR: dict[str, tuple[str, str]] = {
    "360ONE": ("Financial Services", "Wealth Management"),
    "ABB": ("Capital Goods", "Power Equipment"),
    "ABCAPITAL": ("Financial Services", "NBFC / Diversified"),
    "ADANIENSOL": ("Power", "Transmission"),
    "ADANIENT": ("Diversified", "Conglomerate / Infra"),
    "ADANIGREEN": ("Power", "Renewable"),
    "ADANIPORTS": ("Infrastructure", "Ports & Logistics"),
    "ADANIPOWER": ("Power", "Generation"),
    "ALKEM": ("Pharma", "Pharmaceuticals"),
    "AMBER": ("Consumer Durables", "Electronics Manufacturing"),
    "AMBUJACEM": ("Cement", "Cement"),
    "ANGELONE": ("Financial Services", "Broking"),
    "APLAPOLLO": ("Metals & Mining", "Steel Tubes"),
    "APOLLOHOSP": ("Healthcare", "Hospitals"),
    "ASHOKLEY": ("Auto", "Commercial Vehicles"),
    "ASIANPAINT": ("Consumer", "Paints"),
    "ASTRAL": ("Consumer Durables", "Pipes / Building Materials"),
    "AUBANK": ("Banking - Private", "Small Finance Bank"),
    "AUROPHARMA": ("Pharma", "Pharmaceuticals"),
    "AXISBANK": ("Banking - Private", "Private Bank"),
    "BAJAJ-AUTO": ("Auto", "Two Wheelers"),
    "BAJAJFINSV": ("Financial Services", "Insurance / NBFC Holding"),
    "BAJAJHLDNG": ("Financial Services", "Holding Company"),
    "BAJFINANCE": ("Financial Services", "NBFC"),
    "BANDHANBNK": ("Banking - Private", "Private Bank"),
    "BANKBARODA": ("Banking - PSU", "PSU Bank"),
    "BANKINDIA": ("Banking - PSU", "PSU Bank"),
    "BDL": ("Defence", "Defence"),
    "BEL": ("Defence", "Defence Electronics"),
    "BHARATFORG": ("Auto", "Auto Ancillary"),
    "BHARTIARTL": ("Telecom", "Telecom"),
    "BHEL": ("Capital Goods", "Power Equipment"),
    "BIOCON": ("Pharma", "Biotech / Pharmaceuticals"),
    "BLUESTARCO": ("Consumer Durables", "Air Conditioning"),
    "BOSCHLTD": ("Auto", "Auto Ancillary"),
    "BPCL": ("Oil & Gas", "Refining / Marketing"),
    "BRITANNIA": ("FMCG", "Food"),
    "BSE": ("Financial Services", "Exchange"),
    "CAMS": ("Financial Services", "RTA / Fintech Infra"),
    "CANBK": ("Banking - PSU", "PSU Bank"),
    "CDSL": ("Financial Services", "Depository"),
    "CGPOWER": ("Capital Goods", "Power Equipment"),
    "CHOLAFIN": ("Financial Services", "NBFC"),
    "CIPLA": ("Pharma", "Pharmaceuticals"),
    "COALINDIA": ("Metals & Mining", "Coal (PSU)"),
    "COCHINSHIP": ("Defence", "Shipbuilding (PSU)"),
    "COFORGE": ("IT", "IT Services"),
    "COLPAL": ("FMCG", "Personal Care"),
    "CONCOR": ("Infrastructure", "Logistics (PSU)"),
    "CROMPTON": ("Consumer Durables", "Consumer Electricals"),
    "CUMMINSIND": ("Capital Goods", "Industrial Engines"),
    "DABUR": ("FMCG", "Personal Care / Food"),
    "DALBHARAT": ("Cement", "Cement"),
    "DELHIVERY": ("Infrastructure", "Logistics"),
    "DIVISLAB": ("Pharma", "Pharma / API"),
    "DIXON": ("Consumer Durables", "Electronics Manufacturing"),
    "DLF": ("Realty", "Real Estate"),
    "DMART": ("Retail", "Retail (Avenue Supermarts)"),
    "DRREDDY": ("Pharma", "Pharmaceuticals"),
    "EICHERMOT": ("Auto", "Two Wheelers (Royal Enfield)"),
    "ETERNAL": ("Internet / New Age", "Food Delivery / Quick Commerce (Zomato)"),
    "EXIDEIND": ("Auto", "Auto Ancillary (Batteries)"),
    "FEDERALBNK": ("Banking - Private", "Private Bank"),
    "FORCEMOT": ("Auto", "Commercial Vehicles"),
    "FORTIS": ("Healthcare", "Hospitals"),
    "GAIL": ("Oil & Gas", "Gas Transmission (PSU)"),
    "GLENMARK": ("Pharma", "Pharmaceuticals"),
    "GMRAIRPORT": ("Infrastructure", "Airports"),
    "GODFRYPHLP": ("FMCG", "Tobacco"),
    "GODREJCP": ("FMCG", "Personal Care"),
    "GODREJPROP": ("Realty", "Real Estate"),
    "GRASIM": ("Diversified", "Cement / Chemicals (Birla)"),
    "GVT&D": ("Capital Goods", "Power Transmission Equipment"),  # demerged from Crompton Greaves, best-effort
    "HAL": ("Defence", "Aerospace (PSU)"),
    "HAVELLS": ("Consumer Durables", "Consumer Electricals"),
    "HCLTECH": ("IT", "IT Services"),
    "HDFCAMC": ("Financial Services", "Asset Management"),
    "HDFCBANK": ("Banking - Private", "Private Bank"),
    "HDFCLIFE": ("Insurance", "Life Insurance"),
    "HEROMOTOCO": ("Auto", "Two Wheelers"),
    "HINDALCO": ("Metals & Mining", "Aluminium"),
    "HINDPETRO": ("Oil & Gas", "Refining / Marketing (PSU)"),
    "HINDUNILVR": ("FMCG", "Personal Care / Food"),
    "HINDZINC": ("Metals & Mining", "Zinc / Silver"),
    "HUDCO": ("Financial Services", "Housing Finance (PSU)"),
    "HYUNDAI": ("Auto", "Passenger Vehicles"),
    "ICICIBANK": ("Banking - Private", "Private Bank"),
    "ICICIGI": ("Insurance", "General Insurance"),
    "ICICIPRULI": ("Insurance", "Life Insurance"),
    "IDEA": ("Telecom", "Telecom (Vodafone Idea)"),
    "IDFCFIRSTB": ("Banking - Private", "Private Bank"),
    "IEX": ("Financial Services", "Power / Energy Exchange"),
    "INDHOTEL": ("Consumer Services", "Hotels (Taj/IHCL)"),
    "INDIANB": ("Banking - PSU", "PSU Bank"),
    "INDIGO": ("Aviation", "Airlines"),
    "INDUSINDBK": ("Banking - Private", "Private Bank"),
    "INDUSTOWER": ("Telecom", "Telecom Infrastructure"),
    "INFY": ("IT", "IT Services"),
    "INOXWIND": ("Power", "Renewable (Wind Equipment)"),
    "IOC": ("Oil & Gas", "Refining / Marketing (PSU)"),
    "IREDA": ("Financial Services", "NBFC (Renewable Energy, PSU)"),
    "IRFC": ("Financial Services", "NBFC (Railway, PSU)"),
    "ITC": ("FMCG", "Tobacco / Diversified"),
    "JINDALSTEL": ("Metals & Mining", "Steel"),
    "JIOFIN": ("Financial Services", "NBFC / Fintech"),
    "JSWENERGY": ("Power", "Generation"),
    "JSWSTEEL": ("Metals & Mining", "Steel"),
    "JUBLFOOD": ("Consumer Services", "QSR (Domino's)"),
    "KALYANKJIL": ("Retail", "Jewellery"),
    "KAYNES": ("Capital Goods", "Electronics Manufacturing"),
    "KEI": ("Capital Goods", "Cables & Wires"),
    "KFINTECH": ("Financial Services", "RTA / Fintech Infra"),
    "KOTAKBANK": ("Banking - Private", "Private Bank"),
    "KPITTECH": ("IT", "Auto/Engineering Tech"),
    "LAURUSLABS": ("Pharma", "API / CDMO"),
    "LICHSGFIN": ("Financial Services", "Housing Finance"),
    "LICI": ("Insurance", "Life Insurance (PSU)"),
    "LODHA": ("Realty", "Real Estate (Macrotech)"),
    "LT": ("Capital Goods", "Engineering & Construction"),
    "LTF": ("Financial Services", "NBFC (L&T Finance)"),
    "LTM": ("IT", "IT Services (best-effort mapping, verify)"),
    "LUPIN": ("Pharma", "Pharmaceuticals"),
    "M&M": ("Auto", "Passenger Vehicles / Tractors"),
    "MANAPPURAM": ("Financial Services", "NBFC (Gold Loan)"),
    "MANKIND": ("Pharma", "Pharmaceuticals"),
    "MARICO": ("FMCG", "Personal Care / Food"),
    "MARUTI": ("Auto", "Passenger Vehicles"),
    "MAXHEALTH": ("Healthcare", "Hospitals"),
    "MAZDOCK": ("Defence", "Shipbuilding (PSU)"),
    "MCX": ("Financial Services", "Commodity Exchange"),
    "MFSL": ("Insurance", "Life Insurance Holding (Max)"),
    "MOTHERSON": ("Auto", "Auto Ancillary"),
    "MOTILALOFS": ("Financial Services", "Broking / AMC"),
    "MPHASIS": ("IT", "IT Services"),
    "MUTHOOTFIN": ("Financial Services", "NBFC (Gold Loan)"),
    "NAM-INDIA": ("Financial Services", "Asset Management (Nippon)"),
    "NATIONALUM": ("Metals & Mining", "Aluminium (PSU)"),
    "NAUKRI": ("Internet / New Age", "Internet Classifieds (Info Edge)"),
    "NBCC": ("Capital Goods", "Construction (PSU)"),
    "NESTLEIND": ("FMCG", "Food"),
    "NHPC": ("Power", "Hydro Generation (PSU)"),
    "NMDC": ("Metals & Mining", "Iron Ore (PSU)"),
    "NTPC": ("Power", "Generation (PSU)"),
    "NUVAMA": ("Financial Services", "Wealth Management"),
    "NYKAA": ("Internet / New Age", "E-commerce (Beauty)"),
    "OBEROIRLTY": ("Realty", "Real Estate"),
    "OFSS": ("IT", "IT Products (Oracle Financial)"),
    "OIL": ("Oil & Gas", "Exploration & Production (PSU)"),
    "ONGC": ("Oil & Gas", "Exploration & Production (PSU)"),
    "PAGEIND": ("Consumer", "Apparel (Jockey)"),
    "PATANJALI": ("FMCG", "Personal Care / Food"),
    "PAYTM": ("Internet / New Age", "Fintech"),
    "PERSISTENT": ("IT", "IT Services"),
    "PETRONET": ("Oil & Gas", "LNG"),
    "PFC": ("Financial Services", "NBFC (Power, PSU)"),
    "PGEL": ("Consumer Durables", "Electronics Manufacturing (PG Electroplast)"),
    "PHOENIXLTD": ("Realty", "Malls / Real Estate"),
    "PIDILITIND": ("Chemicals", "Adhesives / Consumer Chemicals"),
    "PIIND": ("Chemicals", "Agrochemicals"),
    "PNB": ("Banking - PSU", "PSU Bank"),
    "PNBHOUSING": ("Financial Services", "Housing Finance"),
    "POLICYBZR": ("Internet / New Age", "Insurance/Loan Aggregator"),
    "POLYCAB": ("Consumer Durables", "Cables & Wires"),
    "POWERGRID": ("Power", "Transmission (PSU)"),
    "POWERINDIA": ("Capital Goods", "Power Equipment (Hitachi Energy)"),
    "PREMIERENE": ("Power", "Renewable (Solar Manufacturing)"),
    "PRESTIGE": ("Realty", "Real Estate"),
    "RADICO": ("FMCG", "Alcoholic Beverages"),
    "RBLBANK": ("Banking - Private", "Private Bank"),
    "RECLTD": ("Financial Services", "NBFC (Power, PSU)"),
    "RELIANCE": ("Diversified", "Oil & Gas / Retail / Telecom Conglomerate"),
    "RVNL": ("Capital Goods", "Rail Infrastructure (PSU)"),
    "SAIL": ("Metals & Mining", "Steel (PSU)"),
    "SAMMAANCAP": ("Financial Services", "Housing Finance (formerly Indiabulls HF)"),
    "SBICARD": ("Financial Services", "Credit Cards"),
    "SBILIFE": ("Insurance", "Life Insurance"),
    "SBIN": ("Banking - PSU", "PSU Bank"),
    "SHREECEM": ("Cement", "Cement"),
    "SHRIRAMFIN": ("Financial Services", "NBFC"),
    "SIEMENS": ("Capital Goods", "Industrial Engineering"),
    "SOLARINDS": ("Chemicals", "Explosives / Defence Chemicals"),
    "SONACOMS": ("Auto", "Auto Ancillary (Sona BLW)"),
    "SRF": ("Chemicals", "Specialty Chemicals"),
    "SUNPHARMA": ("Pharma", "Pharmaceuticals"),
    "SUPREMEIND": ("Consumer Durables", "Plastics / Pipes"),
    "SUZLON": ("Power", "Renewable (Wind)"),
    "SWIGGY": ("Internet / New Age", "Food Delivery / Quick Commerce"),
    "TATACONSUM": ("FMCG", "Food & Beverages"),
    "TATAELXSI": ("IT", "Design & Engineering Services"),
    "TATAPOWER": ("Power", "Generation / Distribution"),
    "TATASTEEL": ("Metals & Mining", "Steel"),
    "TCS": ("IT", "IT Services"),
    "TECHM": ("IT", "IT Services"),
    "TIINDIA": ("Auto", "Auto Ancillary (Tube Investments)"),
    "TITAN": ("Retail", "Jewellery / Watches"),
    "TMPV": ("Auto", "Passenger Vehicles (Tata Motors PV, post-demerger)"),
    "TORNTPHARM": ("Pharma", "Pharmaceuticals"),
    "TRENT": ("Retail", "Apparel Retail (Tata - Westside/Zudio)"),
    "TVSMOTOR": ("Auto", "Two Wheelers"),
    "ULTRACEMCO": ("Cement", "Cement"),
    "UNIONBANK": ("Banking - PSU", "PSU Bank"),
    "UNITDSPR": ("FMCG", "Alcoholic Beverages"),
    "UNOMINDA": ("Auto", "Auto Ancillary"),
    "UPL": ("Chemicals", "Agrochemicals"),
    "VBL": ("FMCG", "Beverages (Varun Beverages)"),
    "VEDL": ("Metals & Mining", "Diversified Mining (Vedanta)"),
    "VMM": ("Retail", "Value Retail (Vishal Mega Mart)"),
    "VOLTAS": ("Consumer Durables", "Air Conditioning (Tata)"),
    "WAAREEENER": ("Power", "Renewable (Solar Manufacturing)"),
    "WIPRO": ("IT", "IT Services"),
    "YESBANK": ("Banking - Private", "Private Bank"),
    "ZYDUSLIFE": ("Pharma", "Pharmaceuticals"),
}


def get_sector(symbol: str) -> tuple[str, str]:
    if symbol in INDEX_SYMBOLS:
        return ("Index", INDEX_SYMBOLS[symbol])
    return SYMBOL_SECTOR.get(symbol, ("Unclassified", "Unclassified"))
